function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function dateStr(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

export const DEMO_ACCOUNT = {
  id: "demo-account-1",
  mlUserId: "123456789",
  mlNickname: "LOJA_DEMO_BR",
  mlEmail: "loja@demo.com.br",
  status: "active",
  plan: "professional",
  trialEndsAt: null,
  createdAt: daysAgo(120),
  updatedAt: daysAgo(1),
};

export const DEMO_ME = {
  id: "demo-user-1",
  email: "usuario@demo.com.br",
  plan: "professional",
  trialEndsAt: null,
  createdAt: daysAgo(120),
};

export const DEMO_DASHBOARD_SUMMARY = {
  salesToday: 4382.50,
  salesMonth: 87640.00,
  ordersToday: 18,
  ordersMonth: 342,
  pendingOrders: 7,
  unansweredQuestions: 5,
  criticalStockCount: 4,
  activeAccounts: 1,
};

export const DEMO_SALES_CHART_30D = {
  data: Array.from({ length: 30 }, (_, i) => {
    const dayOffset = 29 - i;
    const base = 2000 + Math.sin(i * 0.4) * 800 + Math.random() * 600;
    const isWeekend = new Date(Date.now() - dayOffset * 86400000).getDay() % 6 === 0;
    return {
      date: dateStr(dayOffset),
      revenue: Math.round((isWeekend ? base * 0.4 : base) * 100) / 100,
      orders: Math.round((isWeekend ? 3 + i % 5 : 8 + i % 12)),
    };
  }),
};

export const DEMO_SALES_CHART_7D = {
  data: DEMO_SALES_CHART_30D.data.slice(-7),
};

export const DEMO_SALES_CHART_90D = {
  data: Array.from({ length: 90 }, (_, i) => {
    const dayOffset = 89 - i;
    const base = 1800 + Math.sin(i * 0.2) * 1000 + (i * 15);
    const isWeekend = new Date(Date.now() - dayOffset * 86400000).getDay() % 6 === 0;
    return {
      date: dateStr(dayOffset),
      revenue: Math.round((isWeekend ? base * 0.4 : base) * 100) / 100,
      orders: Math.round((isWeekend ? 4 + i % 5 : 10 + i % 15)),
    };
  }),
};

export const DEMO_PRODUCTS = [
  {
    id: "demo-prod-1",
    mlItemId: "MLB2345678901",
    title: "Tênis Nike Air Max 270 Masculino Preto",
    sku: "TNK-AIR-270-BLK",
    availableQuantity: 45,
    price: 599.90,
    amount: 499.90,
    regularAmount: 599.90,
    status: "active",
    isFull: true,
    isFlex: false,
    catalogListing: false,
    logisticType: "fulfillment",
    thumbnail: "https://picsum.photos/seed/shoe1/200/200",
    permalink: "https://www.mercadolivre.com.br/tenis-nike",
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-2",
    mlItemId: "MLB2345678902",
    title: "Smartphone Samsung Galaxy A54 128GB Azul",
    sku: "SMS-A54-128-AZL",
    availableQuantity: 12,
    price: 1899.00,
    amount: 1699.00,
    regularAmount: 1899.00,
    status: "active",
    isFull: false,
    isFlex: true,
    catalogListing: true,
    logisticType: "self_service",
    thumbnail: "https://picsum.photos/seed/phone1/200/200",
    permalink: "https://www.mercadolivre.com.br/samsung-a54",
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-3",
    mlItemId: "MLB2345678903",
    title: "Fone de Ouvido Bluetooth JBL Tune 510BT",
    sku: "JBL-T510BT-WHT",
    availableQuantity: 2,
    price: 329.90,
    amount: 289.90,
    regularAmount: null,
    status: "active",
    isFull: false,
    isFlex: false,
    catalogListing: false,
    logisticType: "cross_docking",
    thumbnail: "https://picsum.photos/seed/headphone1/200/200",
    permalink: null,
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-4",
    mlItemId: "MLB2345678904",
    title: "Notebook Lenovo IdeaPad 3i Core i5 8GB 256GB SSD",
    sku: "LNV-IP3I-I5-256",
    availableQuantity: 8,
    price: 2799.00,
    amount: 2499.00,
    regularAmount: 2799.00,
    status: "active",
    isFull: true,
    isFlex: false,
    catalogListing: true,
    logisticType: "fulfillment",
    thumbnail: "https://picsum.photos/seed/laptop1/200/200",
    permalink: "https://www.mercadolivre.com.br/notebook-lenovo",
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-5",
    mlItemId: "MLB2345678905",
    title: "Cadeira Gamer ThunderX3 EC3 Preta e Vermelha",
    sku: "TX3-EC3-BLK-RED",
    availableQuantity: 0,
    price: 1199.00,
    amount: 1199.00,
    regularAmount: null,
    status: "paused",
    isFull: false,
    isFlex: false,
    catalogListing: false,
    logisticType: "cross_docking",
    thumbnail: "https://picsum.photos/seed/chair1/200/200",
    permalink: null,
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-6",
    mlItemId: "MLB2345678906",
    title: "Monitor LG 24 Full HD 75Hz IPS HDMI",
    sku: "LG-MON-24FHD-75",
    availableQuantity: 23,
    price: 999.00,
    amount: 899.00,
    regularAmount: 999.00,
    status: "active",
    isFull: true,
    isFlex: false,
    catalogListing: false,
    logisticType: "fulfillment",
    thumbnail: "https://picsum.photos/seed/monitor1/200/200",
    permalink: "https://www.mercadolivre.com.br/monitor-lg",
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-7",
    mlItemId: "MLB2345678907",
    title: "Câmera IP WiFi Intelbras Full HD 1080p",
    sku: "ITB-CAM-IP1080W",
    availableQuantity: 1,
    price: 349.00,
    amount: 299.00,
    regularAmount: 349.00,
    status: "active",
    isFull: false,
    isFlex: false,
    catalogListing: false,
    logisticType: "cross_docking",
    thumbnail: "https://picsum.photos/seed/camera1/200/200",
    permalink: null,
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-8",
    mlItemId: "MLB2345678908",
    title: "Teclado Mecânico Redragon Kumara K552 RGB",
    sku: "RD-K552-RGB-BRK",
    availableQuantity: 34,
    price: 249.90,
    amount: 219.90,
    regularAmount: 249.90,
    status: "active",
    isFull: false,
    isFlex: true,
    catalogListing: false,
    logisticType: "self_service",
    thumbnail: "https://picsum.photos/seed/keyboard1/200/200",
    permalink: "https://www.mercadolivre.com.br/teclado-redragon",
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-9",
    mlItemId: "MLB2345678909",
    title: "Mouse Logitech G203 LIGHTSYNC RGB 8000DPI",
    sku: "LGT-G203-LSYNC",
    availableQuantity: 67,
    price: 159.00,
    amount: 139.00,
    regularAmount: 159.00,
    status: "active",
    isFull: true,
    isFlex: false,
    catalogListing: true,
    logisticType: "fulfillment",
    thumbnail: "https://picsum.photos/seed/mouse1/200/200",
    permalink: "https://www.mercadolivre.com.br/mouse-logitech",
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-10",
    mlItemId: "MLB2345678910",
    title: "SSD Kingston A400 480GB 2.5 SATA III",
    sku: "KST-A400-480GB",
    availableQuantity: 3,
    price: 229.00,
    amount: 189.00,
    regularAmount: 229.00,
    status: "active",
    isFull: false,
    isFlex: false,
    catalogListing: false,
    logisticType: "cross_docking",
    thumbnail: "https://picsum.photos/seed/ssd1/200/200",
    permalink: null,
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-11",
    mlItemId: "MLB2345678911",
    title: "Impressora HP DeskJet 2776 Multifuncional WiFi",
    sku: "HP-DJ2776-WIFI",
    availableQuantity: 15,
    price: 499.00,
    amount: 449.00,
    regularAmount: 499.00,
    status: "active",
    isFull: false,
    isFlex: true,
    catalogListing: false,
    logisticType: "self_service",
    thumbnail: "https://picsum.photos/seed/printer1/200/200",
    permalink: "https://www.mercadolivre.com.br/impressora-hp",
    accountId: "demo-account-1",
  },
  {
    id: "demo-prod-12",
    mlItemId: "MLB2345678912",
    title: "Suporte de Notebook Ajustável Alumínio Ergonômico",
    sku: "SUP-NOTE-ALU-ERG",
    availableQuantity: 0,
    price: 129.90,
    amount: 99.90,
    regularAmount: 129.90,
    status: "closed",
    isFull: false,
    isFlex: false,
    catalogListing: false,
    logisticType: "cross_docking",
    thumbnail: "https://picsum.photos/seed/stand1/200/200",
    permalink: null,
    accountId: "demo-account-1",
  },
];

export const DEMO_LOW_STOCK_PRODUCTS = DEMO_PRODUCTS.filter(
  (p) => p.availableQuantity !== null && p.availableQuantity < 5
);

export const DEMO_ORDERS = [
  {
    id: "demo-order-1",
    mlOrderId: "3987654321001",
    status: "paid",
    totalAmount: 499.90,
    currencyId: "BRL",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678901", title: "Tênis Nike Air Max 270 Masculino Preto", quantity: 1, price: 499.90, thumbnail: "https://picsum.photos/seed/shoe1/200/200", sku: "TNK-AIR-270-BLK", logistic_type: "fulfillment" },
    ],
  },
  {
    id: "demo-order-2",
    mlOrderId: "3987654321002",
    status: "confirmed",
    totalAmount: 1699.00,
    currencyId: "BRL",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678902", title: "Smartphone Samsung Galaxy A54 128GB Azul", quantity: 1, price: 1699.00, thumbnail: "https://picsum.photos/seed/phone1/200/200", sku: "SMS-A54-128-AZL", logistic_type: "self_service" },
    ],
  },
  {
    id: "demo-order-3",
    mlOrderId: "3987654321003",
    status: "cancelled",
    totalAmount: 289.90,
    currencyId: "BRL",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678903", title: "Fone de Ouvido Bluetooth JBL Tune 510BT", quantity: 1, price: 289.90, thumbnail: "https://picsum.photos/seed/headphone1/200/200", sku: "JBL-T510BT-WHT", logistic_type: "cross_docking" },
    ],
  },
  {
    id: "demo-order-4",
    mlOrderId: "3987654321004",
    status: "paid",
    totalAmount: 4998.00,
    currencyId: "BRL",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678904", title: "Notebook Lenovo IdeaPad 3i Core i5 8GB 256GB SSD", quantity: 2, price: 2499.00, thumbnail: "https://picsum.photos/seed/laptop1/200/200", sku: "LNV-IP3I-I5-256", logistic_type: "fulfillment" },
    ],
  },
  {
    id: "demo-order-5",
    mlOrderId: "3987654321005",
    status: "payment_required",
    totalAmount: 899.00,
    currencyId: "BRL",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678906", title: "Monitor LG 24 Full HD 75Hz IPS HDMI", quantity: 1, price: 899.00, thumbnail: "https://picsum.photos/seed/monitor1/200/200", sku: "LG-MON-24FHD-75", logistic_type: "fulfillment" },
    ],
  },
  {
    id: "demo-order-6",
    mlOrderId: "3987654321006",
    status: "confirmed",
    totalAmount: 439.80,
    currencyId: "BRL",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678908", title: "Teclado Mecânico Redragon Kumara K552 RGB", quantity: 2, price: 219.90, thumbnail: "https://picsum.photos/seed/keyboard1/200/200", sku: "RD-K552-RGB-BRK", logistic_type: "self_service" },
    ],
  },
  {
    id: "demo-order-7",
    mlOrderId: "3987654321007",
    status: "paid",
    totalAmount: 278.00,
    currencyId: "BRL",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678909", title: "Mouse Logitech G203 LIGHTSYNC RGB 8000DPI", quantity: 2, price: 139.00, thumbnail: "https://picsum.photos/seed/mouse1/200/200", sku: "LGT-G203-LSYNC", logistic_type: "fulfillment" },
    ],
  },
  {
    id: "demo-order-8",
    mlOrderId: "3987654321008",
    status: "paid",
    totalAmount: 449.00,
    currencyId: "BRL",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678911", title: "Impressora HP DeskJet 2776 Multifuncional WiFi", quantity: 1, price: 449.00, thumbnail: "https://picsum.photos/seed/printer1/200/200", sku: "HP-DJ2776-WIFI", logistic_type: "self_service" },
    ],
  },
  {
    id: "demo-order-9",
    mlOrderId: "3987654321009",
    status: "payment_required",
    totalAmount: 188.00,
    currencyId: "BRL",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678910", title: "SSD Kingston A400 480GB 2.5 SATA III", quantity: 1, price: 188.00, thumbnail: "https://picsum.photos/seed/ssd1/200/200", sku: "KST-A400-480GB", logistic_type: "cross_docking" },
    ],
  },
  {
    id: "demo-order-10",
    mlOrderId: "3987654321010",
    status: "confirmed",
    totalAmount: 2499.00,
    currencyId: "BRL",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    accountId: "demo-account-1",
    account: { id: "demo-account-1", mlNickname: "LOJA_DEMO_BR", mlUserId: "123456789" },
    itemsJson: [
      { item_id: "MLB2345678904", title: "Notebook Lenovo IdeaPad 3i Core i5 8GB 256GB SSD", quantity: 1, price: 2499.00, thumbnail: "https://picsum.photos/seed/laptop1/200/200", sku: "LNV-IP3I-I5-256", logistic_type: "fulfillment" },
    ],
  },
];

export const DEMO_QUESTIONS = [
  {
    id: "demo-q-1",
    mlItemId: "MLB2345678902",
    text: "Esse celular vem com carregador na caixa? É compatível com carregador de 25W?",
    fromUserNickname: "COMPRADOR_RS_2024",
    status: "unanswered",
    answerText: null,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-2",
    mlItemId: "MLB2345678901",
    text: "Tênis disponível no número 42? Qual o prazo de entrega para São Paulo?",
    fromUserNickname: "JOGADOR_SP_PRIME",
    status: "unanswered",
    answerText: null,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-3",
    mlItemId: "MLB2345678904",
    text: "O notebook aceita upgrade de memória RAM? Vem com Windows instalado?",
    fromUserNickname: "TECH_MINEIRO_PRO",
    status: "unanswered",
    answerText: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-4",
    mlItemId: "MLB2345678908",
    text: "O layout do teclado é ABNT2? Funciona com Mac também?",
    fromUserNickname: "DESIGNR_RIO_DEV",
    status: "unanswered",
    answerText: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-5",
    mlItemId: "MLB2345678906",
    text: "O monitor tem entrada DisplayPort ou apenas HDMI?",
    fromUserNickname: "GAMER_FORTALEZA22",
    status: "unanswered",
    answerText: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-6",
    mlItemId: "MLB2345678909",
    text: "O mouse é sem fio ou com fio? Precisa de dongle USB?",
    fromUserNickname: "USUARIO_BSB_GAMER",
    status: "answered",
    answerText: "Olá! O Logitech G203 é com fio USB, não precisa de dongle. Funciona em plug-and-play em qualquer sistema operacional. Att, Equipe Loja Demo.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-7",
    mlItemId: "MLB2345678903",
    text: "Qual a autonomia da bateria? Tem cancelamento de ruído ativo?",
    fromUserNickname: "MUSIC_LOVER_CTB",
    status: "answered",
    answerText: "Boa tarde! O JBL Tune 510BT tem autonomia de até 40 horas. Ele não possui cancelamento de ruído ativo, mas tem um isolamento passivo eficiente. Abraços!",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-8",
    mlItemId: "MLB2345678911",
    text: "A impressora escaneia em cores? Funciona no Linux Ubuntu?",
    fromUserNickname: "DEVOPS_GYN_2024",
    status: "answered",
    answerText: "Olá! Sim, a HP DeskJet 2776 escaneia em cores. Para Linux, recomendamos verificar os drivers HPLIP disponíveis no site da HP, pois o suporte pode variar por distribuição. Obrigado!",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-9",
    mlItemId: "MLB2345678910",
    text: "O SSD é compatível com notebook Dell Inspiron? Qual a velocidade de leitura?",
    fromUserNickname: "ESTUDANTE_MG_TEC",
    status: "answered",
    answerText: "Olá! O Kingston A400 480GB é compatível com qualquer notebook com slot 2.5\" SATA III, incluindo Dell Inspiron. Velocidade de leitura até 500MB/s. Qualquer dúvida, pode perguntar!",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
    accountId: "demo-account-1",
  },
  {
    id: "demo-q-10",
    mlItemId: "MLB2345678907",
    text: "A câmera grava em cartão SD ou apenas na nuvem? Tem visão noturna?",
    fromUserNickname: "SECURITY_HOME_PA",
    status: "answered",
    answerText: "Bom dia! A câmera Intelbras suporta gravação em cartão microSD (até 128GB) e também em nuvem via app iMHDX. Possui visão noturna infravermelha até 30 metros. Att!",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
    accountId: "demo-account-1",
  },
];

export const DEMO_NOTIFICATIONS = [
  {
    id: "demo-notif-1",
    type: "low_stock",
    title: "Estoque crítico: Fone JBL Tune 510BT",
    message: "O produto JBL-T510BT-WHT está com apenas 2 unidades em estoque. Recomendamos repor o estoque urgentemente.",
    isRead: false,
    resourceType: "product",
    resourceId: "demo-prod-3",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(0),
  },
  {
    id: "demo-notif-2",
    type: "new_order",
    title: "Novo pedido recebido #3987654321001",
    message: "Tênis Nike Air Max 270 Masculino Preto — 1 un. — R$ 499,90",
    isRead: false,
    resourceType: "order",
    resourceId: "demo-order-1",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(0),
  },
  {
    id: "demo-notif-3",
    type: "new_question",
    title: "Nova pergunta no anúncio Samsung Galaxy A54",
    message: "COMPRADOR_RS_2024 perguntou: Esse celular vem com carregador na caixa?",
    isRead: false,
    resourceType: "question",
    resourceId: "demo-q-1",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(0),
  },
  {
    id: "demo-notif-4",
    type: "low_stock",
    title: "Estoque crítico: SSD Kingston A400 480GB",
    message: "O produto KST-A400-480GB está com apenas 3 unidades em estoque.",
    isRead: false,
    resourceType: "product",
    resourceId: "demo-prod-10",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(1),
  },
  {
    id: "demo-notif-5",
    type: "new_order",
    title: "Novo pedido recebido #3987654321002",
    message: "Smartphone Samsung Galaxy A54 128GB Azul — 1 un. — R$ 1.699,00",
    isRead: false,
    resourceType: "order",
    resourceId: "demo-order-2",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(1),
  },
  {
    id: "demo-notif-6",
    type: "order_update",
    title: "Pedido #3987654321003 cancelado",
    message: "O pedido do Fone de Ouvido JBL foi cancelado pelo comprador.",
    isRead: true,
    resourceType: "order",
    resourceId: "demo-order-3",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(2),
  },
  {
    id: "demo-notif-7",
    type: "sync_complete",
    title: "Sincronização concluída com sucesso",
    message: "342 produtos e 45 pedidos sincronizados para a conta LOJA_DEMO_BR.",
    isRead: true,
    resourceType: null,
    resourceId: null,
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(3),
  },
  {
    id: "demo-notif-8",
    type: "low_stock",
    title: "Estoque crítico: Câmera IP Intelbras",
    message: "O produto ITB-CAM-IP1080W está com apenas 1 unidade em estoque.",
    isRead: true,
    resourceType: "product",
    resourceId: "demo-prod-7",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(4),
  },
  {
    id: "demo-notif-9",
    type: "item_update",
    title: "Anúncio pausado: Cadeira Gamer ThunderX3",
    message: "O anúncio TX3-EC3-BLK-RED foi pausado automaticamente por falta de estoque.",
    isRead: true,
    resourceType: "product",
    resourceId: "demo-prod-5",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(5),
  },
  {
    id: "demo-notif-10",
    type: "new_order",
    title: "Novo pedido recebido #3987654321007",
    message: "Mouse Logitech G203 LIGHTSYNC RGB — 2 un. — R$ 278,00",
    isRead: true,
    resourceType: "order",
    resourceId: "demo-order-7",
    accountNickname: "LOJA_DEMO_BR",
    createdAt: daysAgo(5),
  },
];
