// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/products/V1CommandCenter.tsx": () => import("../components/mockups/products/V1CommandCenter.tsx"),
  "./components/mockups/products/V2CommerceGrid.tsx": () => import("../components/mockups/products/V2CommerceGrid.tsx"),
  "./components/mockups/products/V3HealthDashboard.tsx": () => import("../components/mockups/products/V3HealthDashboard.tsx"),
  "./components/mockups/products/V4FocusList.tsx": () => import("../components/mockups/products/V4FocusList.tsx"),
  "./components/mockups/products/V5BentoSignal.tsx": () => import("../components/mockups/products/V5BentoSignal.tsx")
};
